### ISSUE TITLE
现在登陆有验证码了，有办法过吗

### ISSUE THREAD

**Issue by white52** [tuchief/SMZDM_check_in#1]
刚刚试了一下没有成功😫

**Comment by tuchief** [comment]
@white52 可以使用session来登录

不建议使用自动化工具，什么值得买升级了作弊检测，发现会被封号的，乖乖手动吧😆

**Comment by white52** [comment]
噢噢，谢谢你的提醒但是在我的印象中我貌似没有弄过这个，你能说说这个的具体的用途吗
